import PrimeLogo from './PrimeLogo';
import {ServiceContent,serviceRoutes} from './ServicePages';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpLeft,ArrowUpRight,UserRound,LockKeyhole,Globe,LayoutGrid,Database,Moon,Sun,Monitor,Mail,LogOut,Pencil,Activity,FileText,ShieldCheck,ChevronLeft,X,CalendarDays,Cookie,Download,Trash2,KeyRound,MapPin,Clock,Hash} from 'lucide-react';
import Modal,{ModalCloseButton} from './Modal';
import {notify} from './Alerts';
import './account.css';
import CookieNotice from './CookieNotice';
const rowIcons={'E-mail':Mail,'Assinatura':LayoutGrid,'Conta criada':CalendarDays,'Tema':Sun,'Login com senha':LockKeyhole,'Códigos de recuperação':KeyRound,'Configurações de cookies':Cookie,'Baixar dados da conta':Download,'Excluir conta':Trash2};
const sections=[['account','Conta',UserRound],['security','Segurança',LockKeyhole],['sessions','Sessões',Globe],['apps','Apps conectados',LayoutGrid],['data','Dados',Database]];
function date(value,month='short'){if(!value)return 'Não informado';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'Não informado':parsed.toLocaleDateString('pt-BR',{day:'numeric',month,year:'numeric'})}
function browserSession(){const ua=navigator.userAgent;return {id:'current',current:true,browser:/Edg\//.test(ua)?'Edge':/Firefox\//.test(ua)?'Firefox':/Chrome\//.test(ua)?'Chrome':/Safari\//.test(ua)?'Safari':'Navegador',os:/Android/.test(ua)?'Android':/iPhone|iPad/.test(ua)?'iOS':/Mac/.test(ua)?'macOS':/Windows/.test(ua)?'Windows':/Linux/.test(ua)?'Linux':'Não informado',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,client:'Web'}}
function SessionMap({session}){
 if(session.mapImageUrl)return <div className="account-session-map"><img src={session.mapImageUrl} alt={`Mapa da região de ${session.city||'sua sessão'}`}/></div>;
 const hasLocation=Number.isFinite(session.latitude)&&Number.isFinite(session.longitude);
 if(!hasLocation)return null;
 const lat=session.latitude,lon=session.longitude;
 const query=new URLSearchParams({bbox:`${lon-.34},${lat-.16},${lon+.34},${lat+.16}`,layer:'mapnik'});
 return <div className="account-session-map"><iframe title={hasLocation?'Mapa da localização da sessão':'Mapa de exemplo de São Paulo'} src={`https://www.openstreetmap.org/export/embed.html?${query}`} loading="lazy" referrerPolicy="no-referrer" tabIndex={-1}/><span className="account-map-position" aria-hidden="true"/><a className="account-map-credit" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap</a>{!hasLocation&&<span className="account-map-caption">Mapa de exemplo</span>}</div>
}
function SessionDetails({session}){return <><SessionMap session={session}/><dl className="account-session-details">{[['Cidade',session.city],['Região',session.region],['País',session.country],['Fuso horário',session.timezone],['Endereço IP',session.ip],['Sistema operacional',session.os],['Navegador',session.browser],['Cliente',session.client]].map(([label,value])=><React.Fragment key={label}><dt><span className="account-session-detail-icon" aria-hidden="true">{['Cidade','Região','País'].includes(label)?<MapPin size={18}/>:label==='Fuso horário'?<Clock size={18}/>:label==='Endereço IP'?<Hash size={18}/>:<Monitor size={18}/>}</span>{label}</dt><dd>{value||'Não informado'}</dd></React.Fragment>)}</dl></>}
function BrowserIcon({browser}){return browser==='Chrome'?<svg viewBox="0 0 24 24" width="17" height="17" aria-hidden="true" fill="currentColor"><path d="M12 1a11 11 0 0 1 9.8 6H12a5 5 0 0 0-4.3 2.5L4.3 3.4A10.9 10.9 0 0 1 12 1Zm10.4 7.5A11 11 0 0 1 12 23l4.9-8.5a5 5 0 0 0 0-6h5.5ZM10.3 22.9A11 11 0 0 1 3.2 4.6l4.9 8.5a5 5 0 0 0 7.2 3.2l-5 6.6Z"/><circle cx="12" cy="12" r="3.5"/></svg>:<Globe size={17}/>}
export default function Account({initialResource=null,profile,onProfileChange,theme,setTheme,onReturn,onBack,onUpgrade,plan='Free',accountData,onDefinePassword,onSignOut,onRevokeSession,onDeleteAccount,onExportData}){
 const [resource,setResource]=useState(initialResource||new URLSearchParams(location.search).get('secao'));
 function openResource(id){setResource(id);setModal(null);const url=new URL(location.href);url.pathname=serviceRoutes[id]||'/conta';url.search='';history.pushState(null,'',url);main.current?.scrollTo({top:0,behavior:'instant'})}
 useEffect(()=>{const sync=()=>setResource(Object.keys(serviceRoutes).find(id=>serviceRoutes[id]===location.pathname)||new URLSearchParams(location.search).get('secao'));window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 const [section,setSection]=useState('account'),[modal,setModal]=useState(null),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState('');
 const main=useRef(null),photo=useRef(null),sectionRefs=useRef({});
 const [current]=useState(browserSession);
 const [deleteEmail,setDeleteEmail]=useState(''),[deleting,setDeleting]=useState(false);
 const canDelete=Boolean(profile.email)&&deleteEmail.trim().toLowerCase()===profile.email.trim().toLowerCase();
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[savingPassword,setSavingPassword]=useState(false);
 const sessions=accountData?.sessions||[current],currentSession=sessions.find(s=>s.current)||current;
 useEffect(()=>{if(resource)return;const container=main.current;let frame;const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const top=container.getBoundingClientRect().top+110;let active='account';for(const [id] of sections){if(sectionRefs.current[id]?.getBoundingClientRect().top<=top)active=id}if(container.scrollHeight-container.scrollTop-container.clientHeight<10)active='data';setSection(active)})};container.addEventListener('scroll',sync,{passive:true});sync();return()=>{container.removeEventListener('scroll',sync);cancelAnimationFrame(frame)}},[resource]);
 function go(id){if(resource){setResource(null);const url=new URL(location.href);url.pathname='/conta';url.search='';history.pushState(null,'',url);setSection(id);requestAnimationFrame(()=>sectionRefs.current[id]?.scrollIntoView({block:'start'}));return}sectionRefs.current[id]?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});setSection(id)}
 function editName(){const names=(profile.name||'').trim().split(/\s+/);setFirstName(names.shift()||'');setLastName(names.join(' '));setModal('name')}
 async function persistProfile(next){try{await onProfileChange(next);notify('Perfil atualizado','success');return true}catch{notify('Não foi possível salvar o perfil');return false}}
 async function saveName(e){e.preventDefault();if(!firstName.trim())return;if(await persistProfile({...profile,name:[firstName.trim(),lastName.trim()].filter(Boolean).join(' ')}))setModal(null)}
 async function changePhoto(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){notify('Selecione uma imagem JPG, PNG ou WebP de até 5 MB');return}const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=384;const ctx=canvas.getContext('2d'),side=Math.min(image.width,image.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,384,384);ctx.drawImage(image,(image.width-side)/2,(image.height-side)/2,side,side,0,0,384,384);await persistProfile({...profile,avatar:canvas.toDataURL('image/jpeg',.88)})}catch{notify('Não foi possível carregar a imagem')}finally{URL.revokeObjectURL(url)}}
 async function exportData(){try{const data=await onExportData();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prime-dados.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{notify('Não foi possível baixar os dados')}}
 function notIntegrated(){notify('Essa ação precisa da integração com a conta Prime','info')}
 function definePassword(){setPassword('');setConfirmation('');setModal('password')}
 async function savePassword(e){e.preventDefault();if(!onDefinePassword||password.length<8||password!==confirmation)return;setSavingPassword(true);try{await onDefinePassword(password);setPassword('');setConfirmation('');setModal(null);notify('Senha atualizada','success')}catch{notify('Não foi possível atualizar a senha')}finally{setSavingPassword(false)}}
 function openDelete(){setDeleteEmail('');setModal('delete')}
 function closeModal(){if(!deleting)setModal(null)}
 async function confirmDelete(e){e.preventDefault();if(!canDelete||deleting)return;if(!onDeleteAccount){notIntegrated();return}setDeleting(true);try{await onDeleteAccount(deleteEmail);setDeleteEmail('');setModal(null)}catch{notify('Não foi possível excluir a conta. Tente novamente.')}finally{setDeleting(false)}}
 const row=(label,description,content,action)=>{const Icon=rowIcons[label]||UserRound;return <div className="account-row"><div className="account-row-label"><Icon className="account-row-icon" size={20} aria-hidden="true"/><span>{label}</span>{description&&<p>{description}</p>}</div><div className="account-row-end">{content}{action}</div></div>};
 const button=(label,onClick,extra='')=><button type="button" className={`account-button ${extra}`} onClick={onClick}>{label}</button>;
 const panel=(id,children)=><section className="account-section" id={`account-${id}`} ref={el=>{sectionRefs.current[id]=el}} aria-labelledby={`account-heading-${id}`}>{children}</section>;
 const heading=(id,action)=><header className="account-section-header"><h1 id={`account-heading-${id}`}>{sections.find(s=>s[0]===id)[1]}</h1>{action}</header>;
 return <div className="account-page">
  <aside className="account-sidebar"><nav className="mobile-account-navigation" aria-label="Navegação da tela"><button className="mobile-circle-control" aria-label={resource?"Voltar à conta":"Voltar às configurações"} onClick={resource?()=>go('account'):onBack||onReturn}><ChevronLeft size={22}/></button><button className="mobile-circle-control" aria-label="Fechar gerenciamento de conta" onClick={onReturn}><X size={21}/></button></nav><div className="account-wordmark"><PrimeLogo/></div><button className="account-return" onClick={onReturn}><ArrowUpLeft size={16}/><span>Retornar para <span>Prime</span></span></button>
   <nav aria-label="Navegação da conta">{sections.map(([id,label,Icon])=><button key={id} aria-current={!resource&&section===id?'page':undefined} onClick={()=>go(id)}><Icon size={17}/>{label}</button>)}</nav>
   <div className="account-app-label">Apps</div><div className="account-resources"><button onClick={onReturn}><LayoutGrid size={17}/>Prime</button>{[[ShieldCheck,'Política de privacidade','privacy'],[FileText,'Termos de uso','terms'],[Activity,'Status do serviço','status']].map(([Icon,label,id])=><button key={id} aria-current={resource===id?'page':undefined} onClick={()=>openResource(id)}><Icon size={17}/>{label}</button>)}</div>
   <button className="account-signout" onClick={()=>setModal('signout')}><LogOut size={17}/>Sair</button>
  </aside>
  <main className="account-main" ref={main}>
   {resource?<ServiceContent type={resource}/>:<>
   {panel('account',<>{heading('account')}<div className="account-mobile-card"><div className="account-row account-profile-row"><div className="account-profile"><button className="account-avatar-edit" aria-label="Trocar foto do perfil" onClick={()=>photo.current.click()}><img src={profile.avatar||'/images/avatar.svg'} alt=""/><span><Pencil size={15}/></span></button><input ref={photo} className="account-file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={changePhoto}/><span>{profile.name}</span></div>{button('Alterar',editName)}</div>
    {row('E-mail',null,<span className="account-email">{profile.email}</span>)}
    {row('Assinatura',null,<span className="account-muted">{{monthly:'SuperPrime',lifetime:'SuperPrime Heavy',founder:'Fundador',admin:'Administrador'}[plan]||plan||'Não informado'}</span>,button(<>Gerenciar <ArrowUpRight size={15}/></>,onUpgrade))}
    {row('Conta criada',null,<span className="account-muted">{date(accountData?.createdAt||profile.createdAt,'long')}</span>)}
    {row('Tema',null,<div className="account-theme" aria-label="Tema">{[['dark','Tema escuro',Moon],['light','Tema claro',Sun],['system','Tema do sistema',Monitor]].map(([id,label,Icon])=><button key={id} aria-label={label} aria-pressed={theme===id} onClick={()=>setTheme(id)}><Icon size={20}/></button>)}</div>)}
    </div><h2>Métodos de login</h2><div className="account-login-methods"><div className="account-row"><div className="account-login-label"><span className="account-provider-icon"><Mail size={18}/></span><span>Entrar com e-mail e senha</span></div>{button(accountData?.passwordEnabled?'Gerenciar':'Ativar',definePassword,'account-button-primary')}</div></div></>)}
   {panel('security',<>{heading('security')}<div className="account-mobile-card">{row('Login com senha','Gerencie a senha da sua conta.',null,button(accountData?.passwordEnabled?'Alterar senha':'Definir senha',definePassword))}{row('Códigos de recuperação',null,<span className="account-muted">Nenhum código disponível</span>)}</div></>)}
   {panel('sessions',<>{heading('sessions',button('Sair de todos os dispositivos',()=>setModal('all-sessions')))}<h2>Sessão atual</h2><div className="account-session-current"><SessionDetails session={currentSession}/></div><h2>Sessões ativas</h2><div className="account-session-table"><div className="account-session-table-head"><span>Cliente</span><span>Localização</span><span>Criado em</span><span>Expira em</span><span/></div>{sessions.map(session=><button key={session.id} className="account-session-row" onClick={()=>setModal({type:'session',session})}><span><Monitor size={17}/><BrowserIcon browser={session.browser}/>{session.browser||'Web'}</span><span>{session.city||'Não informado'}</span><span>{date(session.createdAt)}</span><span>{date(session.expiresAt)}</span><ArrowUpRight size={16}/></button>)}</div></>)}
   {panel('apps',<>{heading('apps')}<p className="account-apps-description">Aplicativos autorizados a acessar sua conta.</p><div className="account-empty account-mobile-card"><LayoutGrid className="account-empty-icon" size={26} aria-hidden="true"/><span>Nada conectado ainda</span></div></>)}
   {panel('data',<>{heading('data')}<div className="account-mobile-card">{row('Configurações de cookies','Gerencie suas preferências de cookies para análises e publicidade.',null,button('Gerenciar',()=>setModal('cookies')))}{row('Baixar dados da conta','Baixe os dados disponíveis neste dispositivo.',null,button('Baixar',exportData))}{row('Excluir conta','Exclua sua conta e os dados associados.',null,button('Excluir',openDelete,'account-button-danger'))}</div></>)}
   </>}
   <section className="account-mobile-apps" aria-labelledby="account-mobile-apps-heading">
    <h1 id="account-mobile-apps-heading">Apps</h1>
    <div className="account-mobile-app-links">
     <button onClick={onReturn}><LayoutGrid size={20}/><span>Prime</span><ArrowUpRight size={17}/></button>
     {[[ShieldCheck,'Política de privacidade','privacy'],[FileText,'Termos de uso','terms'],[Activity,'Status do serviço','status']].map(([Icon,label,id])=><button key={id} aria-current={resource===id?'page':undefined} onClick={()=>openResource(id)}><Icon size={20}/><span>{label}</span><ArrowUpRight size={17}/></button>)}
     <button onClick={()=>setModal('signout')}><LogOut size={20}/><span>Sair</span></button>
    </div>
   </section>
  </main>
  <CookieNotice showBanner={false} manageOpen={modal==='cookies'} onManageClose={()=>setModal(null)} onLegal={openResource}/>
  {modal&&modal!=='cookies'&&<Modal label={typeof modal==='object'?'Detalhes da sessão':{name:'Editar nome',password:'Definir senha',cookies:'Configurações de cookies',delete:'Excluir conta',signout:'Sair', 'all-sessions':'Sair de todos os dispositivos',privacy:'Política de privacidade',terms:'Termos de uso',status:'Status do serviço'}[modal]} className={`account-edit-modal ${modal==='cookies'?'account-cookie-modal':modal==='delete'?'account-delete-modal':''}`} onClose={closeModal}><header><h2>{typeof modal==='object'?'Detalhes da sessão':{name:'Editar nome',password:'Definir senha',cookies:'Configurações de cookies',delete:'Excluir conta',signout:'Sair', 'all-sessions':'Sair de todos os dispositivos',privacy:'Política de privacidade',terms:'Termos de uso',status:'Status do serviço'}[modal]}</h2><ModalCloseButton onClick={closeModal}/></header>
   {modal==='name'&&<form onSubmit={saveName}><label>Nome<input autoFocus required maxLength={40} value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><label>Sobrenome<input maxLength={60} value={lastName} onChange={e=>setLastName(e.target.value)}/></label><div>{button('Cancelar',()=>setModal(null))}<button className="account-button account-button-primary" type="submit" disabled={!firstName.trim()}>Salvar</button></div></form>}
   {typeof modal==='object'&&<><SessionDetails session={modal.session}/><div className="account-modal-actions">{button('Excluir sessão',async()=>{try{if(onRevokeSession){await onRevokeSession(modal.session.id);closeModal()}else notIntegrated()}catch(e){notify(e.message)}})}</div></>}
   {modal==='password'&&<form onSubmit={savePassword}>{!onDefinePassword&&<p className="account-modal-copy">A definição de senha estará disponível quando o login da conta Prime estiver integrado.</p>}<label>Nova senha<input type="password" autoComplete="new-password" minLength={8} required disabled={!onDefinePassword||savingPassword} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar senha<input type="password" autoComplete="new-password" required disabled={!onDefinePassword||savingPassword} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div>{button('Cancelar',()=>setModal(null))}<button type="submit" className="account-button account-button-primary" disabled={!onDefinePassword||savingPassword||password.length<8||password!==confirmation}>{savingPassword?'Salvando…':'Salvar'}</button></div></form>}
   {modal==='delete'&&<form onSubmit={confirmDelete}><p className="account-delete-copy">Sua conta será excluída após 30 dias. Se você entrar no Prime novamente antes da exclusão, o pedido será cancelado automaticamente. Ao confirmar, você sairá da sua conta.</p><span className="account-delete-email">{profile.email}</span><label>Digite seu e-mail para confirmar<input type="email" autoComplete="off" autoCapitalize="none" spellCheck={false} required placeholder="seu@email.com" value={deleteEmail} disabled={deleting} onChange={e=>setDeleteEmail(e.target.value)}/></label><div className="account-delete-actions"><button type="button" className="account-button" disabled={deleting} onClick={closeModal}>Cancelar</button><button type="submit" className="account-button account-delete-confirm" disabled={!canDelete||deleting}>{deleting?'Solicitando…':'Solicitar exclusão'}</button></div></form>}
   {['signout','all-sessions'].includes(modal)&&<><p className="account-modal-copy">{modal==='signout'?'Deseja sair da sua conta?':'Deseja encerrar as sessões em todos os dispositivos?'}</p><div className="account-modal-actions">{button('Cancelar',()=>setModal(null))}{button('Sair',async()=>{try{if(onSignOut)await onSignOut(modal==='all-sessions'?'all':'current');else notIntegrated()}catch(e){notify(e.message)}},'account-button-primary')}</div></>}
   {['privacy','terms','status'].includes(modal)&&<><p className="account-modal-copy">{modal==='status'?'O monitoramento do serviço ainda não está conectado.':'O documento oficial será disponibilizado aqui.'}</p><div className="account-modal-actions">{button('Fechar',()=>setModal(null))}</div></>}
  </Modal>}
 </div>
}
