import {normalizeProfile,validatedAffiliateUrl,mapSavedProducts,mapSessions} from './backend-contract.mjs';
import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {supabase} from './supabase-client';
import {loadStores} from './store-data';
import LoadingScreen from './LoadingScreen';
export {supabase} from './supabase-client';
const Context=createContext(null);
export const useBackend=()=>useContext(Context);
export function BackendProvider({children}){
 const [state,setState]=useState({ready:false,user:null,profile:null,access:null,saved:{},products:[],error:null,recovery:false,catalogReady:false,catalogError:null,stores:[],sessions:[],preferences:{},storesError:null});
 const generation=useRef(0),mounted=useRef(true);
 const [loading,setLoading]=useState('');
 async function blocking(label,action){setLoading(label);try{return await action()}finally{setLoading('')}}
 async function accountProfile(user,row){const profile=normalizeProfile(user,row),path=user.user_metadata?.prime_avatar_path;if(path?.startsWith(`${user.id}/`)){const {data,error}=await supabase.storage.from('prime-avatars').createSignedUrl(path,3600);if(!error)profile.avatar=data.signedUrl}return profile}
 async function hydrate(session,event){
  const version=++generation.current;
  if(!session?.user){setState(s=>({...s,ready:true,user:null,profile:null,access:null,saved:{},stores:[],sessions:[],error:null,recovery:false}));return}
  const user=session.user;
  try{
   const results=await Promise.all([supabase.from('profiles').select('first_name,last_name,created_at').eq('id',user.id).single(),supabase.from('saved_products').select('product_id,affiliate_url').eq('user_id',user.id),supabase.rpc('get_my_access'),supabase.rpc('get_my_prime_sessions'),supabase.from('user_preferences').select('theme,language').eq('user_id',user.id).maybeSingle()]);
   for(const result of results)if(result.error)throw result.error;
   if(!results[3].data.some(session=>session.is_current)){await supabase.auth.signOut({scope:'local'});await hydrate(null);return}
   if(!mounted.current||generation.current!==version)return;
   const profile=await accountProfile(user,results[0].data);
   if(!mounted.current||generation.current!==version)return;
   setState(s=>({...s,ready:true,user,profile,saved:mapSavedProducts(results[1].data),sessions:mapSessions(results[3].data),preferences:{...results[4].data,...user.user_metadata?.prime_v2_preferences},access:results[2].data?.[0]||{has_access:false},error:null,recovery:event==='PASSWORD_RECOVERY'||user.user_metadata?.prime_needs_password===true||s.recovery}));
  if(results[2].data?.[0]?.has_access){try{const stores=await loadStores();if(mounted.current&&version===generation.current)setState(s=>({...s,stores,storesError:null}))}catch{if(mounted.current&&version===generation.current)setState(s=>({...s,stores:[],storesError:'Não foi possível carregar suas lojas.'}))}}
 }catch{if(mounted.current&&version===generation.current)setState(s=>({...s,ready:true,user:null,profile:null,access:null,saved:{},error:'Não foi possível carregar sua conta. Tente novamente.'}))}
 }
 useEffect(()=>{
  mounted.current=true;
  if(!supabase){setState(s=>({...s,ready:true,error:'Configure a conexão com o Supabase para continuar.'}));return}
  let timer;
  const {data}=supabase.auth.onAuthStateChange((event,session)=>{clearTimeout(timer);timer=setTimeout(()=>hydrate(session,event),0)});
  supabase.auth.getSession().then(({data,error})=>error?setState(s=>({...s,ready:true,error:'Não foi possível recuperar sua sessão.'})):hydrate(data.session));
  (async()=>{try{let products=[],page=0;while(true){const {data,error}=await supabase.from('products').select('*').eq('is_active',true).order('id').range(page*1000,page*1000+999);if(error)throw error;products.push(...data);if(data.length<1000)break;page++}if(mounted.current)setState(s=>({...s,catalogReady:true,catalogError:null,products:products.map(p=>({...p,image_url:p.image_url||p.source_image_url}))}))}catch{if(mounted.current)setState(s=>({...s,catalogReady:true,catalogError:'Não foi possível carregar o catálogo. Tente novamente.'}))}})();
  return()=>{mounted.current=false;clearTimeout(timer);generation.current++;data.subscription.unsubscribe()};
 },[]);
 useEffect(()=>{const sync=()=>{const version=generation.current;loadStores().then(stores=>{if(mounted.current&&generation.current===version)setState(s=>({...s,stores,storesError:null}))}).catch(()=>{if(mounted.current&&generation.current===version)setState(s=>({...s,storesError:'Não foi possível atualizar suas lojas.'}))})};window.addEventListener('prime-v2-stores-updated',sync);return()=>window.removeEventListener('prime-v2-stores-updated',sync)},[]);
 useEffect(()=>{if(!state.user)return;let running=false;const check=async()=>{if(running)return;running=true;try{const version=generation.current;const [access,sessions]=await Promise.all([supabase.rpc('get_my_access'),supabase.rpc('get_my_prime_sessions')]);if(!access.error&&!sessions.error&&mounted.current&&version===generation.current){if(!sessions.data.some(session=>session.is_current)){await signOut();return}setState(s=>({...s,access:access.data?.[0]||{has_access:false},sessions:mapSessions(sessions.data)}))}}catch{}finally{running=false}};const timer=setInterval(check,60000);const visible=()=>{if(document.visibilityState==='visible')check()};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[state.user?.id]);
 useEffect(()=>{const path=state.user?.user_metadata?.prime_avatar_path;if(!path)return;const timer=setInterval(async()=>{const profile=await accountProfile(state.user,{});if(mounted.current)setState(s=>s.user?.id===state.user.id?{...s,profile:{...s.profile,avatar:profile.avatar}}:s)},1800000);return()=>clearInterval(timer)},[state.user?.id,state.user?.user_metadata?.prime_avatar_path]);
 function requireAccount(){if(!state.user||!state.access?.has_access)throw new Error('Entre com uma conta com acesso ativo para continuar.');return state.user}
 async function loginAction({email,password}){const {data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){const failure=new Error(error.code==='invalid_credentials'?'E-mail ou senha incorretos.':'Não foi possível entrar. Confira seu e-mail e tente novamente.');failure.code=error.code;throw failure}await hydrate(data.session);}
 async function registerAction({email,password,name}){email=email.trim().toLowerCase();const eligibility=await supabase.rpc('check_signup_eligibility',{p_email:email});if(eligibility.error)throw new Error('Não foi possível verificar sua compra.');if(!eligibility.data)throw new Error('Nenhuma compra aprovada e ativa foi encontrada para este e-mail.');const [first_name,...rest]=name.trim().split(/\s+/);const {data,error}=await supabase.auth.signUp({email,password,options:{data:{first_name,last_name:rest.join(' ')},emailRedirectTo:`${location.origin}/entrar`}});if(error){if(['user_already_exists','email_exists'].includes(error.code)){await resetPassword({email});return {message:'Se você já tem uma conta, enviamos um link para definir sua senha. Confira seu e-mail ou entre com sua senha atual.'}}throw new Error('Não foi possível criar a conta. Verifique se seu e-mail já está cadastrado.');}if(data.session)await hydrate(data.session);return {message:data.session?null:'Conta criada. Confirme o link enviado ao seu e-mail para entrar.'}}
 async function resetPassword({email}){const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${location.origin}/recuperar-senha`});if(error)throw new Error('Não foi possível enviar as instruções. Tente novamente.');}
 async function signOutAction(scope='current'){const {error}=await supabase.auth.signOut({scope:scope==='all'?'global':'local'});if(error)throw new Error('Não foi possível encerrar a sessão.');await hydrate(null);}
 async function updateProfile(next){const user=requireAccount(),[first_name,...rest]=next.name.trim().split(/\s+/);const metadata={first_name,last_name:rest.join(' ')};if(next.avatar?.startsWith('data:image/')){const blob=await (await fetch(next.avatar)).blob();if(blob.size>2097152)throw new Error('A foto precisa ter até 2 MB.');const path=`${user.id}/avatar.${blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg'}`;const uploaded=await supabase.storage.from('prime-avatars').upload(path,blob,{upsert:true,contentType:blob.type});if(uploaded.error)throw new Error('Não foi possível salvar sua foto.');metadata.prime_avatar_path=path;metadata.avatar_url=null}const {data,error}=await supabase.auth.updateUser({data:metadata});if(error)throw new Error('Não foi possível atualizar seu perfil.');const result=await supabase.from('profiles').select('first_name,last_name,created_at').eq('id',user.id).single();if(result.error)throw new Error('Não foi possível recarregar seu perfil.');const profile=await accountProfile(data.user,result.data);setState(s=>({...s,profile,user:data.user}));return profile;}
 async function definePassword(password){if(!state.user)throw new Error('Abra o link de recuperação enviado ao seu e-mail.');const {error}=await supabase.auth.updateUser({password,data:{prime_needs_password:false}});if(error)throw new Error('Não foi possível atualizar sua senha.');setState(s=>({...s,recovery:false}));}
 async function saveLink(productId,value){const user=requireAccount(),link=validatedAffiliateUrl(value);const {error}=await supabase.from('saved_products').upsert({user_id:user.id,product_id:productId,affiliate_url:link},{onConflict:'user_id,product_id'});if(error)throw new Error('Não foi possível salvar seu link. Tente novamente.');setState(s=>({...s,saved:{...s.saved,[productId]:link}}));}

 async function revokeSession(id){requireAccount();const {data,error}=await supabase.rpc('revoke_my_prime_session',{p_session_id:id});if(error||!data)throw new Error('Não foi possível encerrar esta sessão.');if(state.sessions.find(s=>s.id===id)?.current){await signOut()}else setState(s=>({...s,sessions:s.sessions.filter(session=>session.id!==id)}));}
 async function savePreferences(values){const user=requireAccount();const {data,error}=await supabase.auth.updateUser({data:{prime_v2_preferences:{...user.user_metadata?.prime_v2_preferences,...values}}});if(error)throw new Error('Não foi possível salvar suas preferências.');setState(s=>({...s,user:data.user,preferences:{...s.preferences,...values}}));}
 async function exportAccountData(){requireAccount();const [result,analytics]=await Promise.all([supabase.from('saved_products').select('product_id,affiliate_url,created_at,updated_at'),supabase.from('prime_analytics_sessions').select('created_at,last_seen_at,ip,ip_source,user_agent,device,platform,language,timezone,screen_width,screen_height,first_page,last_page,consent')]);if(result.error||analytics.error)throw new Error('Não foi possível exportar seus dados.');return {exportedAt:new Date().toISOString(),profile:state.profile,savedProducts:result.data,preferences:state.preferences,stores:state.stores,analyticsSessions:analytics.data};}
 async function deleteAccount(email){if(!state.user)throw new Error('Entre na sua conta para continuar.');const {data,error}=await supabase.functions.invoke('prime-account',{body:{action:'delete-account',email}});if(error||!data?.scheduled)throw new Error('Não foi possível excluir sua conta. Tente novamente.');await supabase.auth.signOut({scope:'local'});await hydrate(null);}
 const login=values=>blocking('Entrando na sua conta…',()=>loginAction(values));
 const register=values=>blocking('Criando sua conta…',()=>registerAction(values));
 const signOut=scope=>blocking('Saindo da sua conta…',()=>signOutAction(scope));
 return <Context.Provider value={{...state,login,register,resetPassword,signOut,updateProfile,definePassword,saveLink,revokeSession,savePreferences,exportAccountData,deleteAccount,retry:()=>location.reload()}}><div inert={loading?true:undefined} aria-busy={!!loading}>{children}</div>{loading&&<LoadingScreen overlay label={loading}/>}</Context.Provider>;
}
