import React,{useRef,useState} from 'react';
import {X,Upload,Image as ImageIcon,FileText} from 'lucide-react';
import Modal,{ModalCloseButton} from './Modal';
import {notify} from './Alerts';
import ReasonMenu from './ReasonMenu';
function saveComment(report){return new Promise((resolve,reject)=>{const request=indexedDB.open('prime-v2-feedback',1);request.onupgradeneeded=()=>request.result.createObjectStore('comments',{keyPath:'id'});request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error());request.onsuccess=()=>{const db=request.result;try{const transaction=db.transaction('comments','readwrite');transaction.objectStore('comments').add(report);transaction.oncomplete=()=>{db.close();resolve()};transaction.onerror=()=>{db.close();reject(transaction.error)};transaction.onabort=()=>{db.close();reject(transaction.error)}}catch(error){db.close();reject(error)}}})}
export default function Feedback({onClose}){
 const [reason,setReason]=useState(''),[message,setMessage]=useState(''),[files,setFiles]=useState([]),[dragging,setDragging]=useState(false),[sending,setSending]=useState(false);
 const input=useRef(null);
 function attach(incoming){const additions=Array.from(incoming).filter(file=>!files.some(existing=>existing.name===file.name&&existing.size===file.size&&existing.lastModified===file.lastModified));if(files.length+additions.length>5){notify('Adicione no máximo 5 anexos');return}if(additions.some(file=>file.size>10*1024*1024)){notify('Cada anexo deve ter até 10 MB');return}setFiles(current=>[...current,...additions])}
 async function submit(e){e.preventDefault();if(!reason||!message.trim()||sending)return;setSending(true);try{await saveComment({id:crypto.randomUUID(),reason,message:message.trim(),attachments:files,createdAt:new Date().toISOString()});notify('Comentário salvo neste navegador','success');onClose()}catch{notify('Não foi possível salvar o comentário');setSending(false)}}
 return <Modal label="Reportar conteúdo" className="feedback-modal" onClose={onClose}><header><h2>Reportar conteúdo</h2><ModalCloseButton label="Fechar comentário" onClick={onClose}/></header><form onSubmit={submit}><label id="feedback-reason-label" className="feedback-reason-label" htmlFor="feedback-reason">Motivo</label><ReasonMenu value={reason} onChange={setReason}/><textarea data-autofocus="true" aria-label="Diga-nos o que está errado" required placeholder="Diga-nos o que está errado" value={message} onChange={e=>setMessage(e.target.value)} rows={8}/><div className="feedback-attachments-label">Anexos <span>({files.length}/5)</span></div><button className={`feedback-dropzone ${dragging?'is-dragging':''}`} type="button" onClick={()=>input.current.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);attach(e.dataTransfer.files)}}><Upload size={22} strokeWidth={1.8}/><span>Arraste e solte ou clique para selecionar</span></button><input ref={input} type="file" multiple hidden aria-label="Selecionar anexos" onChange={e=>{attach(e.target.files);e.target.value=''}}/>{files.length>0&&<ul className="feedback-file-list">{files.map((file,i)=><li key={`${file.name}-${file.lastModified}`}><span className="feedback-file-icon" aria-hidden="true">{file.type.startsWith('image/')?<ImageIcon size={16}/>:<FileText size={16}/>}</span><span title={file.name}>{file.name}</span><button type="button" aria-label={`Remover ${file.name}`} onClick={()=>setFiles(current=>current.filter((_,index)=>index!==i))}><X size={14}/></button></li>)}</ul>}<div className="feedback-actions"><button type="submit" disabled={!reason||!message.trim()||sending}>{sending?'Salvando...':'Enviar'}</button></div></form></Modal>
}
