import React from 'react';
import StatusDashboard from './StatusDashboard';
import PrimeLogo from './PrimeLogo';
import './service-pages.css';
export const serviceRoutes={privacy:'/privacidade',terms:'/termos',status:'/status'};
const documents={
 privacy:{title:'Política de privacidade',intro:'Como o Prime utiliza informações na experiência atual da plataforma.',sections:[
 ['Informações utilizadas','O Prime utiliza os dados de perfil que você informa, como nome, e-mail e foto, além de preferências de tema, produtos salvos, links e lojas criadas. Imagens e textos selecionados por você são usados para preparar o conteúdo solicitado.'],
 ['Armazenamento no navegador','Os dados da conta, produtos salvos e lojas ficam no Supabase. Cookies e armazenamento local lembram escolhas de privacidade e preferências do navegador. Limpar os dados do site remove essas escolhas locais, mas não apaga os produtos salvos na conta.'],
 ['Finalidades','Essas informações permitem personalizar a interface, organizar seus produtos, preparar lojas e materiais de divulgação e lembrar suas escolhas de privacidade. Com sua permissão para análises, registramos sessões de navegação para entender o uso do Prime. Não há ferramenta de publicidade de terceiros conectada.'],
 ['Sessões e segurança','O Supabase registra as sessões autenticadas, IP e navegador do login para manter o acesso e permitir encerrar sessões em Gerenciar conta. Esses registros essenciais de autenticação são separados das análises opcionais. Os dados de análises não têm leitura pública; contas autenticadas só podem consultar seus próprios registros.'],
 ['Serviços externos','Imagens do catálogo são carregadas pelo serviço de armazenamento Supabase. Links de ofertas podem levar à Shopee, e a contratação dos planos ocorre no checkout Applyfy. Esses provedores recebem as informações necessárias à navegação, como endereço IP, e tratam os dados informados em suas páginas segundo suas próprias políticas. O Prime não recebe dados de cartão por meio destes links.'],
 ['Cookies e preferências','Você pode aceitar, rejeitar ou configurar categorias opcionais no aviso de cookies. A escolha é mantida em um cookie próprio e no armazenamento local, evitando repetir o aviso. Fechar o aviso mantém apenas cookies essenciais. As preferências podem ser alteradas em Configurações de cookies. Permitir análises ativa o registro de IP recebido pelo servidor, navegador, tipo de aparelho, idioma, fuso horário, tamanho da tela e páginas visitadas, sem parâmetros de URL. Identificadores aleatórios distinguem o navegador e a sessão. Rejeitar análises interrompe novos registros opcionais. A preferência de publicidade não ativa uma integração que não esteja instalada.'],
 ['Seus dados e direitos','Você pode editar seu perfil e baixar os dados disponíveis em Gerenciar conta → Dados. A exportação inclui os registros de análises associados à sua conta. Ao solicitar a exclusão, a conta é agendada para remoção após 30 dias. Um novo login antes da remoção cancela o pedido automaticamente. A LGPD prevê direitos como acesso, correção, informação sobre compartilhamento e, nas hipóteses aplicáveis, eliminação e revogação do consentimento.'],
 ['Atualizações','Esta política descreve a implementação atual. Novas integrações ou alterações de finalidade devem ser refletidas neste documento antes de sua ativação.']
 ]},
 terms:{title:'Termos de uso',intro:'Condições para utilizar as ferramentas do Prime.',sections:[
 ['O que é o Prime','O Prime reúne um catálogo de produtos e ferramentas para organizar ofertas, criar lojas e preparar conteúdo de divulgação. O Prime não é o vendedor dos produtos anunciados e não substitui as condições das plataformas de venda ou dos programas de afiliados.'],
 ['Conta e acesso','Utilize informações corretas e mantenha suas credenciais protegidas. Dados de perfil, produtos salvos e lojas são mantidos na sua conta Prime, no Supabase. Recursos demonstrativos não representam uma operação concluída em serviços externos.'],
 ['Planos e pagamento','SuperPrime custa R$ 169 por mês. SuperPrime Heavy oferece acesso vitalício por R$ 299 à vista; valores e encargos de parcelamento são apresentados no checkout. Confira o preço total, a periodicidade e as condições antes de pagar. Acesso vitalício corresponde a uma contratação sem mensalidade para o produto contratado, sem afastar direitos legais do consumidor.'],
 ['Compras, cancelamento e suporte','Os pagamentos são realizados no checkout externo. Consulte os dados do vendedor e os canais de suporte apresentados no checkout ou no comprovante para pedidos de cancelamento, reembolso e questões sobre a compra. As condições contratuais não afastam os direitos assegurados pela legislação aplicável.'],
 ['Uso responsável','Não utilize o Prime para fraude, spam, anúncios enganosos, violação de privacidade ou de direitos autorais. Publique apenas conteúdo e imagens que você tenha autorização para usar e siga as regras dos grupos, redes sociais e programas de afiliados.'],
 ['Ofertas e resultados','Preços, estoque, comissão e condições de entrega são definidos pelos vendedores e podem mudar. Verifique a oferta antes de divulgar. O Prime não garante vendas, renda ou aprovação em programas de afiliados. Revise textos e materiais gerados antes de publicar.'],
 ['Disponibilidade e dados locais','A página de status mostra verificações disponíveis a partir do seu navegador, sem representar uma garantia de disponibilidade. Mantenha cópias dos seus materiais: limpar o armazenamento do navegador pode remover o conteúdo local.'],
 ['Privacidade e alterações','O tratamento de dados é descrito na Política de privacidade. Alterações relevantes nestas condições devem ser informadas na plataforma.']
 ]}
};
export function ServiceContent({type}){const doc=documents[type];return <div className="service-content"><h1>{doc?.title||'Status do serviço'}</h1>{doc?<><p className="service-intro">{doc.intro}</p><p className="service-updated">Atualizado em 5 de outubro de 2026</p>{doc.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}{type==='privacy'&&<p><a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm" target="_blank" rel="noopener noreferrer">Consultar a LGPD</a></p>}</>:<StatusDashboard/>}</div>}
export default function ServicePages({type}){return <div className="service-page"><header><a href="/" aria-label="Prime, início"><PrimeLogo/></a><a href="/conta">Voltar à conta</a></header><main><ServiceContent type={type}/></main></div>}
