import React,{useEffect,useState} from 'react';
import {Check,Minus,TriangleAlert} from 'lucide-react';
const backendUrl=import.meta.env.VITE_SUPABASE_URL;
const backendKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const checks=[{id:'web',label:'Prime Web',url:'/',kind:'app'},{id:'assets',label:'Arquivos',url:'/images/prime-brand.png',kind:'image'},{id:'supplier',label:'Catálogo',url:`${backendUrl}/rest/v1/products?select=id&limit=1`,kind:'json',headers:{apikey:backendKey}},{id:'auth',label:'Login',url:`${backendUrl}/auth/v1/health`,kind:'json'}];
const services=[
 {id:'web',name:'Prime Web',description:'Acesso ao Prime pelo navegador.'},
 {id:'auth',name:'Login e cadastro',description:'Entrada e criação da sua conta.'},
 {id:'videos',name:'Criação de vídeos',description:'Preparação de prompts, roteiros e imagens para seus vídeos.'},
 {id:'supplier',name:'Fornecedor',description:'Consulta aos produtos e imagens do catálogo.'},
 {id:'shopee',name:'Conexão com a Shopee',description:'Conexão da sua conta de afiliado.',status:'Em demonstração'},
 {id:'groups',name:'Grupos do Facebook',description:'Encontre grupos para divulgar seus produtos.'},
 {id:'templates',name:'Templates e stories',description:'Modelos e materiais para personalizar sua divulgação.'},
 {id:'stores',name:'Lojas',description:'Criação e acesso às suas lojas online.'},
];
export default function StatusDashboard(){
 const [results,setResults]=useState([]),[samples,setSamples]=useState([]),[checked,setChecked]=useState(null),[busy,setBusy]=useState(true);
 useEffect(()=>{let disposed=false,running=false;const controllers=new Set();async function check(){if(running||disposed)return;running=true;setBusy(true);const next=await Promise.all(checks.map(async service=>{const controller=new AbortController();controllers.add(controller);const timeout=setTimeout(()=>controller.abort(),10000),start=performance.now();try{const response=await fetch(service.url,{cache:'no-store',signal:controller.signal,headers:service.headers});if(!response.ok)throw Error();if(service.kind==='app'&&!(await response.text()).includes('id="root"'))throw Error();if(service.kind==='json'){await response.json()}if(service.kind==='image'){if(!response.headers.get('content-type')?.startsWith('image/'))throw Error();await response.arrayBuffer()}return {...service,ok:true,ms:Math.round(performance.now()-start)}}catch{return {...service,ok:false}}finally{clearTimeout(timeout);controllers.delete(controller)}}));running=false;if(!disposed){setResults(next);setSamples(old=>[...old,next].slice(-20));setChecked(new Date());setBusy(false)}}check();const interval=setInterval(check,30000);window.addEventListener('online',check);window.addEventListener('offline',check);return()=>{disposed=true;clearInterval(interval);controllers.forEach(c=>c.abort());window.removeEventListener('online',check);window.removeEventListener('offline',check)}},[]);
 const healthy=results.length===checks.length&&results.every(r=>r.ok),loading=!checked,Icon=loading?Minus:healthy?Check:TriangleAlert;
 return <div className="status-dashboard">
  <div className={`status-incident ${loading?'pending':healthy?'healthy':'warning'}`} role="status"><span className="status-incident-icon"><Icon size={21} strokeWidth={2.5}/></span><div><strong>{loading?'Verificando o acesso ao Prime':healthy?'Serviços verificados acessíveis':'Dificuldade de acesso detectada'}</strong><p>{loading?'Aguarde enquanto verificamos o acesso.':healthy?'Confira abaixo a situação de cada recurso do Prime.':'Não foi possível confirmar o acesso a todos os recursos verificados. Tentaremos novamente automaticamente.'}</p></div></div>
  <section className="status-live"><h2>Dados do serviço em tempo real</h2><p>Verificações a cada 30 segundos. Sucesso indica a proporção de verificações concluídas nesta sessão; resposta é o tempo de carregamento em milissegundos.</p>
   <div className="status-matrix"><div className="status-matrix-scroll"><table><thead><tr><th rowSpan="2" scope="col">Origem</th><th colSpan={checks.length} scope="colgroup">Serviço</th></tr><tr>{checks.map(c=><th key={c.id} scope="col">{c.label}</th>)}</tr></thead><tbody><tr><th scope="row">Este navegador</th>{checks.map(c=>{const result=results.find(r=>r.id===c.id),observations=samples.map(s=>s.find(r=>r.id===c.id)).filter(Boolean),rate=observations.length?observations.filter(r=>r.ok).length/observations.length*100:null;return <td key={c.id}><div className="status-measurements"><div className={`status-measure ${rate===null?'pending':rate===100?'healthy':rate>=95?'warning':'failed'}`}><strong>{rate===null?'—':`${Number(rate.toFixed(2)).toLocaleString('pt-BR')}%`}</strong><span>Sucesso</span></div><div className={`status-measure ${!result?'pending':!result.ok?'failed':result.ms>2000?'warning':'healthy'}`}><strong>{result?.ms!==undefined?`${result.ms} ms`:'—'}</strong><span>Resposta</span></div></div></td>})}</tr></tbody></table></div><div className="status-matrix-footer" aria-live="polite"><span>{samples.length} {samples.length===1?'amostra':'amostras'} nesta sessão</span><span>{busy&&checked?'Atualizando…':checked?`Atualizado às ${checked.toLocaleTimeString('pt-BR')}`:'Aguardando primeira verificação'}</span></div></div>
  </section>
  <section className="status-services"><h2>Serviços do Prime</h2><p className="status-intro">Acompanhe os recursos que você usa no dia a dia.</p><div className="status-service-grid">{services.map(service=>{const result=results.find(r=>r.id===service.id),monitored=checks.some(c=>c.id===service.id);const label=service.status||(!monitored?'Status não informado':!result?'Verificando':!result.ok?'Falha ao verificar':service.id==='supplier'?'Catálogo acessível':'Disponível');const tone=result?.ok?'healthy':result?'warning':'pending';return <div className="status-service-card" key={service.id}><span>{service.name}</span><span className={`status-pill ${tone}`}>{label}</span></div>})}</div><p className="status-scope">As medições verificam o Prime Web, um arquivo da interface, a consulta ao catálogo e a saúde do serviço de autenticação a partir da sua conexão. Não executam um cadastro nem um login completo. Não representam a disponibilidade de todas as funções ou um histórico global. Os demais recursos ainda não têm informações de disponibilidade integradas. “Status não informado” não significa que o recurso esteja fora do ar.</p></section>
 </div>;
}
