import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ChevronLeft,Pencil,Upload,Plus,Check,X,ArrowUpRight,ImagePlus,Store} from 'lucide-react';
import {useBackend} from './Backend';
import Storefront,{BannerArt,bannerPresets,storeTemplates,normalize} from './Storefront';
import Modal,{ModalCloseButton} from './Modal';
import AffiliateLinkModal from './AffiliateLinkModal';
import StoreTemplateMenu from './StoreTemplateMenu';
import {notify} from './Alerts';
import {createStore} from './store-data';
import useStoreHistory from './useStoreHistory';
import {safeStoreUrl,contrastingText,affiliateLinkReady} from './store-links.mjs';
function Color({label,value,onChange,onCommit}){return <label className="sb-color"><span>{label}</span><div><input type="color" aria-label={label} value={value} onInput={e=>onChange(e.target.value)} onChange={e=>onChange(e.target.value)} onBlur={onCommit}/><span>{value.toUpperCase()}</span></div></label>}
export default function StoreEditor({store,onClose}){
 const {products}=useBackend(),history=useStoreHistory(store),{draft,change:setDraft,undo,redo,endGroup,markPublished,dirty}=history;
 const [panel,setPanel]=useState(null),[bannerMenu,setBannerMenu]=useState(null),[busy,setBusy]=useState(false);
 const [identity,setIdentity]=useState({name:store.name,description:store.description||'',logo:store.logo||''}),[item,setItem]=useState(null),[link,setLink]=useState(''),[linkError,setLinkError]=useState('');
 const [query,setQuery]=useState(''),[picked,setPicked]=useState([]),[address,setAddress]=useState(store.domain||'');
 const logoInput=useRef(null),bannerInput=useRef(null),backgroundInput=useRef(null),saving=useRef(false),bannerMenuRef=useRef(null);
 useEffect(()=>{if(!bannerMenu)return;const outside=e=>{if(!bannerMenuRef.current?.contains(e.target)&&!e.target.closest('.sf2-banner-hit'))setBannerMenu(null)};const keys=e=>{if(e.key==='Escape')setBannerMenu(null)};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keys);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keys)}},[bannerMenu]);
 const ids=draft.productIds||[],update=(key,value)=>setDraft(d=>({...d,[key]:value}),['accent','buttonText','background','text','overlay'].includes(key)?`field:${key}`:null);
 useEffect(()=>{const shortcuts=e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||e.defaultPrevented)return;const target=e.target,typing=target.isContentEditable||target.closest('textarea')||target.closest('input:not([type=color]):not([type=range])');if(typing)return;const key=e.key.toLowerCase();if(key==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(key==='y'&&e.ctrlKey){e.preventDefault();redo()}};window.addEventListener('keydown',shortcuts);return()=>window.removeEventListener('keydown',shortcuts)},[undo,redo]);
 async function upload(e,field){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){notify('Escolha uma imagem JPG, PNG ou WebP de até 8 MB');return}try{const url=URL.createObjectURL(file);let image;try{image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}finally{URL.revokeObjectURL(url)}const scale=Math.min(1,(field==='logo'?512:1400)/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/webp',.82);if(field==='logo'&&panel==='identity')setIdentity(v=>({...v,logo:data}));else update(field,data)}catch{notify('Não foi possível carregar a imagem')}}
 function edit(section,product,point){
  if(section==='banner'){setBannerMenu({left:Math.max(8,Math.min(point?.x||window.innerWidth/2,window.innerWidth-184)),top:Math.min(point?.y||80,window.innerHeight-(window.matchMedia('(pointer:coarse)').matches?108:80))});return}
  if(section==='removeProducts'){setDraft(d=>{const next=d.productIds.filter(id=>!product.includes(id));return {...d,productIds:next,categories:(d.categories||[]).filter(c=>products.some(p=>next.includes(p.id)&&p.category===c)),affiliateLinks:Object.fromEntries(Object.entries(d.affiliateLinks||{}).filter(([id])=>!product.includes(id)))}});return}
  if(section==='logo'){setIdentity({name:draft.name,description:draft.description||'',logo:draft.logo||''});setPanel('identity');return}
  if(section==='identity'){setIdentity({name:draft.name,description:draft.description||'',logo:draft.logo||''});setPanel('identity');return}
  if(section==='product'){setItem(product);setLink(draft.affiliateLinks?.[product.id]||'');setLinkError('');setPanel('link');return}
  if(section==='removeProduct'){setDraft(d=>{const next=d.productIds.filter(id=>id!==product.id);return {...d,productIds:next,categories:(d.categories||[]).filter(c=>products.some(p=>next.includes(p.id)&&p.category===c)),affiliateLinks:Object.fromEntries(Object.entries(d.affiliateLinks||{}).filter(([id])=>id!==product.id))}});return}
  if(section==='products'||section==='addProducts'){setPicked([]);setQuery('');setPanel('products');return}
  setPanel(section==='banner'?'banner':'colors');
 }
 function saveIdentity(e){e.preventDefault();if(!identity.name.trim()){notify('Informe o nome da loja');return}setDraft(d=>({...d,name:identity.name.trim(),description:identity.description,logo:identity.logo}));setPanel(null)}
 function saveLink(e){e.preventDefault();const url=safeStoreUrl(link);if(!url||url===safeStoreUrl(item.source_url)){setLinkError('Cole seu link de afiliado, diferente do link original do produto.');return}setDraft(d=>({...d,affiliateLinks:{...d.affiliateLinks,[item.id]:url}}));setPanel(null)}
 function addProducts(){const added=products.filter(p=>picked.includes(p.id));setDraft(d=>({...d,productIds:[...new Set([...d.productIds,...picked])],categories:[...new Set([...(d.categories||[]),...added.map(p=>p.category)])]}));setPanel(null)}
 async function publish(domain=draft.domain){if(saving.current)return;if(!ids.length){notify('Adicione pelo menos um produto');return}if(!domain){setAddress('');setPanel('address');return}saving.current=true;setBusy(true);try{const submitted=draft;const result=await createStore({...submitted,domain,status:'published'},ids);markPublished(result,submitted);setPanel(null);notify('Alterações publicadas','success')}catch(e){notify(e.message)}finally{saving.current=false;setBusy(false)}}
 const names={identity:'Editar identidade',link:item&&affiliateLinkReady(draft,item)?'Editar link':'Obter link',banner:'Trocar banner',products:'Adicionar produtos',colors:'Aparência da loja',address:'Publicar loja',background:'Escolher fundo'};
 return createPortal(<><section className="store-live-editor" tabIndex={-1} aria-label={`Editor de ${draft.name}`} style={{'--editor-bg':draft.background||'#fff','--editor-text':draft.text||'#222','--editor-publish-bg':contrastingText(draft.background||'#ffffff'),'--editor-publish-text':contrastingText(contrastingText(draft.background||'#ffffff'))}}>

 <nav className="store-editor-floating" aria-label="Controles da edição" style={{'--editor-publish-bg':contrastingText(draft.background||'#ffffff'),'--editor-publish-text':contrastingText(contrastingText(draft.background||'#ffffff'))}}><button className="store-editor-back" aria-label="Voltar às lojas" onClick={onClose}><ChevronLeft size={21}/></button><div><button className="store-editor-publish" disabled={busy} onClick={()=>publish()}>{busy?'Publicando…':'Publicar'}</button></div></nav>
 <p className="store-editor-live-status" role="status" aria-live="polite">{history.action==='undo'?'Edição desfeita. ':history.action==='redo'?'Edição refeita. ':''}{dirty?'Alterações na prévia. Clique em Publicar para salvar.':'Nenhuma alteração pendente.'}</p>
 <Storefront store={draft} onEdit={edit}/>
 {[[logoInput,'logo'],[bannerInput,'banner'],[backgroundInput,'backgroundImage']].map(([ref,key])=><input key={key} ref={ref} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e,key)}/>)}
 {bannerMenu&&<div ref={bannerMenuRef} className="store-banner-menu" role="menu" aria-label="Opções do banner" style={bannerMenu}><button role="menuitem" onClick={()=>{setBannerMenu(null);setPanel('banner')}}>Escolher na galeria</button><button role="menuitem" onClick={()=>{setBannerMenu(null);bannerInput.current.click()}}>Enviar meu banner</button></div>}
 {panel&&panel!=='link'&&<Modal overlayClassName="store-editor-overlay" label={names[panel]} className={`store-edit-dialog ${panel==='colors'?'store-appearance-dialog':''} ${panel==='products'?'store-product-picker':''} ${['banner','background'].includes(panel)?'sb-gallery-modal':''}`} onClose={()=>setPanel(null)}><header><h2>{names[panel]}</h2><ModalCloseButton onClick={()=>setPanel(null)}/></header>
 {panel==='identity'&&<form onSubmit={saveIdentity}><div className="store-identity-logo"><button type="button" className="store-identity-avatar" aria-label="Trocar logo da loja" onClick={()=>logoInput.current.click()}>{identity.logo?<img src={identity.logo} alt="Logo da loja"/>:<Store size={30} aria-hidden="true"/>}<span className="store-identity-avatar-overlay" aria-hidden="true"><Pencil size={21}/></span></button></div><label className="sb-input">Nome da loja<input autoFocus value={identity.name} maxLength={60} onChange={e=>setIdentity(v=>({...v,name:e.target.value}))}/></label><label className="sb-input">Descrição<textarea rows={4} maxLength={240} value={identity.description} onChange={e=>setIdentity(v=>({...v,description:e.target.value}))}/></label><button type="button" className="store-identity-appearance" onClick={()=>setPanel('colors')}>Cores e fundo da loja</button><div className="sb-actions"><button type="button" onClick={()=>setPanel(null)}>Cancelar</button><button className="store-primary-action">Aplicar</button></div></form>}
 {['banner','background'].includes(panel)&&<><p>{panel==='background'?'Escolha uma cor de fundo ou envie sua imagem.':'Escolha um banner para a sua loja.'}</p><button className="sb-upload-banner" onClick={()=>{setPanel(null);(panel==='background'?backgroundInput:bannerInput).current.click()}}><Upload size={16}/>{panel==='background'?'Enviar imagem de fundo':'Enviar meu banner'}</button><div className="sb-gallery-grid">{bannerPresets.map(b=><button key={b.id} onClick={()=>{setDraft(d=>panel==='background'?{...d,backgroundImage:'',background:b.background}:{...d,banner:'',bannerPreset:b.id});setPanel(null)}}><BannerArt preset={b.id}/><span>{b.name}</span></button>)}</div></>}
 {panel==='products'&&<><input autoFocus className="store-picker-search" aria-label="Pesquisar produtos para adicionar" placeholder="Pesquisar produtos" value={query} onChange={e=>setQuery(e.target.value)}/><div className="store-picker-grid store-picker-list">{products.filter(p=>normalize(p.name).includes(normalize(query))).map(p=><button key={p.id} disabled={ids.includes(p.id)} aria-pressed={picked.includes(p.id)||ids.includes(p.id)} aria-label={`Adicionar ${p.name}`} onClick={()=>setPicked(v=>v.includes(p.id)?v.filter(id=>id!==p.id):[...v,p.id])}><div><img loading="lazy" src={p.image_url} alt=""/><span>{(picked.includes(p.id)||ids.includes(p.id))&&<Check size={15}/>}</span></div><div className="store-picker-product-info"><strong>{p.name}</strong><small>{ids.includes(p.id)?'Já está na loja':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(p.price_cents/100)}</small></div></button>)}</div><div className="sb-actions"><button onClick={()=>setPanel(null)}>Cancelar</button><button className="store-primary-action" disabled={!picked.length} onClick={addProducts}>Adicionar{picked.length?` (${picked.length})`:''}</button></div></>}
 {panel==='colors'&&<><div className="sb-field-section">{[['accent','Cor dos botões'],['buttonText','Cor do texto dos botões'],['background','Cor do fundo'],['text','Cor do texto']].map(([key,label])=><Color key={key} label={label} value={draft[key]||(key==='buttonText'?contrastingText(draft.accent):'#ffffff')} onChange={value=>update(key,value)} onCommit={endGroup}/>)}</div><div className="sb-field-section"><StoreTemplateMenu value={draft.template} onChange={value=>update('template',value)}/>{[['cardTheme','Fundo dos cards']].map(([key,label])=><div className="sb-theme-control" key={key}><span>{label}</span><div>{[['light','Da loja'],['dark','Escuro']].map(([value,text])=><button key={value} aria-pressed={draft[key]===value} onClick={()=>update(key,value)}>{text}</button>)}</div></div>)}<label className="sb-range">Escurecer banner<span>{draft.overlay||0}%</span><input type="range" aria-label="Escurecer banner" min="0" max="80" step="5" value={draft.overlay||0} style={{'--range-progress':`${(draft.overlay||0)/80*100}%`}} onChange={e=>update('overlay',Number(e.target.value))} onPointerUp={endGroup} onKeyUp={endGroup} onBlur={endGroup}/></label><button className="sb-upload-banner" onClick={()=>setPanel('background')}><ImagePlus size={16}/>Escolher fundo</button>{draft.backgroundImage&&<button onClick={()=>update('backgroundImage','')}>Remover imagem de fundo</button>}</div><div className="sb-actions"><button className="store-primary-action" onClick={()=>setPanel(null)}>Concluir</button></div></>}
 {panel==='address'&&<form onSubmit={e=>{e.preventDefault();publish(address)}}><label className="sb-input">Endereço da loja<input autoFocus value={address} pattern="[a-z0-9]+(-[a-z0-9]+)*" minLength={3} maxLength={63} required placeholder="minha-loja" onChange={e=>setAddress(normalize(e.target.value).replace(/[^a-z0-9-]/g,''))}/></label><div className="sb-actions"><button className="store-primary-action" disabled={busy}>Publicar</button></div></form>}
 </Modal>}
 {panel==='link'&&<AffiliateLinkModal key={item.id} product={item} value={link} onChange={value=>{setLink(value);setLinkError('')}} onSubmit={saveLink} onClose={()=>setPanel(null)} editing={affiliateLinkReady(draft,item)} error={linkError} overlayClassName="store-editor-overlay"/>}
 </section></>,document.body);
}
