import {notify} from './Alerts';
import React,{useState,useRef,useEffect} from 'react';
import {HugeiconsIcon} from '@hugeicons/react';
import {Store01Icon,Search01Icon} from '@hugeicons/core-free-icons';
import {Check,Upload,X,Monitor,Smartphone,ChevronDown,MoreHorizontal,ArrowUpRight,Image as ImageIcon} from 'lucide-react';
import {useBackend} from './Backend';
import Storefront,{TemplateThumbnail,storeTemplates,bannerPresets,BannerArt,productColorFields,defaultProductColors,resolveProductColors,normalize} from './Storefront';
import Modal,{ModalCloseButton} from './Modal';
import {createStore,deleteStore} from './store-data';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const slugify=value=>normalize(value).replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,63);
const newDraft=()=>({name:'',title:'',description:'',domain:'',logo:'',banner:'',backgroundImage:'',bannerPreset:'blue',accent:'#171717',background:'#ffffff',text:'#222222',overlay:0,cardTheme:'light',categoryTheme:'light',categories:[],template:'essential',productColors:{},productColorMode:'store',status:'draft'});
const steps=['Produtos','Template','Personalização','Identidade','Página do produto','Revisão'];
function ColorControl({label,value,onChange}){return <label className="sb-color"><span>{label}</span><div><input type="color" aria-label={label} value={value} onInput={e=>onChange(e.target.value)} onChange={e=>onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></label>}
function Preview({store,device,page,onDevice,onPage}){
 const container=useRef(null),[width,setWidth]=useState(500);
 useEffect(()=>{const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));if(container.current)observer.observe(container.current);return()=>observer.disconnect()},[]);
 const logicalWidth=device==='mobile'?390:1100,scale=Math.min(device==='mobile'?.82:1,(width-36)/logicalWidth);
 return <aside className="sb-preview"><div className="sb-preview-toolbar"><div><button aria-label="Prévia desktop" aria-pressed={device==='desktop'} onClick={()=>onDevice('desktop')}><Monitor size={17}/></button><button aria-label="Prévia mobile" aria-pressed={device==='mobile'} onClick={()=>onDevice('mobile')}><Smartphone size={17}/></button></div></div><div className="sb-preview-stage" ref={container}><div className={`sb-preview-device sb-preview-${device}`} style={{width:logicalWidth*scale,height:Math.min(740,device==='mobile'?760:820)*scale}}><div className="sb-preview-scroll" style={{width:logicalWidth,height:(device==='mobile'?760:820),transform:`scale(${scale})`}}><Storefront key={`${device}-${page}`} store={store} previewPage={page}/></div></div></div></aside>
}
export default function Stores({stores,initialCreate=false,initialEdit}){
 const {products}=useBackend();
 const existing=stores.find(s=>s.id===initialEdit),[step,setStep]=useState(existing?1:initialCreate?0:null),[ids,setIds]=useState(existing?.productIds||[]),[query,setQuery]=useState(''),[storeQuery,setStoreQuery]=useState(''),[draft,setDraft]=useState(existing?{...newDraft(),...existing}:newDraft),[device,setDevice]=useState('desktop'),[previewPage,setPreviewPage]=useState('store'),[mediaMenu,setMediaMenu]=useState(null),[gallery,setGallery]=useState(false),[options,setOptions]=useState(null),[publishing,setPublishing]=useState(null),[address,setAddress]=useState(''),[publishBusy,setPublishBusy]=useState(false);
 const saving=useRef(false);
 const logoInput=useRef(null),bannerInput=useRef(null),backgroundInput=useRef(null),optionRoot=useRef(null),mediaRoot=useRef(null);
 useEffect(()=>{if(!options&&!mediaMenu)return;function close(e){if(!optionRoot.current?.contains(e.target))setOptions(null);if(!mediaRoot.current?.contains(e.target))setMediaMenu(null)}document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[options,mediaMenu]);
 const selected=products.filter(p=>ids.includes(p.id)),availableCategories=[...new Set(selected.map(p=>p.category))];
 const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
 function start(){setStep(0);setIds([]);setQuery('');setDraft(newDraft());setPreviewPage('store')}
 async function remove(store){try{await deleteStore(store.id);setOptions(null);notify('Loja excluída','success')}catch(e){notify(e.message)}}
 function edit(store){setOptions(null);setDraft({...newDraft(),...store});setIds(store.productIds||[]);setStep(1);setPreviewPage('store');window.scrollTo({top:0,behavior:'instant'})}
 function move(next){if(next>0&&!ids.length){notify('Selecione pelo menos um produto');return}if(next>3&&!draft.name.trim()){notify('Informe o nome da vitrine');return}setStep(next);setPreviewPage(next===4?'product':'store');window.scrollTo({top:0,behavior:'instant'})}
 async function upload(e,key){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){notify('Escolha uma imagem JPG, PNG ou WebP de até 8 MB');return}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=data});const canvas=document.createElement('canvas'),scale=Math.min(1,(key==='logo'?512:1400)/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);update(key,canvas.toDataURL('image/webp',.82));}catch{notify('Não foi possível carregar a imagem')}}
 async function save(){if(saving.current)return;if(!ids.length||!draft.name.trim()){notify('Preencha a identidade e selecione os produtos');return}saving.current=true;try{await createStore({...draft,title:'',name:draft.name.trim(),categories:draft.categories.filter(c=>availableCategories.includes(c))},ids,location.href);setStep(null);notify('Loja salva','success')}catch(e){notify(e.message)}finally{saving.current=false}}

 async function publish(e){
  e.preventDefault();if(publishBusy)return;
  const domain=slugify(address),store=publishing;
  if(domain.length<3||stores.some(s=>s.id!==store.id&&s.domain===domain)){notify('Escolha um endereço disponível');return}
  setPublishBusy(true);
  try{
   await createStore({...store,domain,status:'published'},store.productIds,location.href);
   setPublishing(null);setPublishBusy(false);setStoreQuery('');window.scrollTo({top:0,behavior:'instant'});notify('Página publicada','success');
  }catch(e){setPublishBusy(false);notify(e.message)}
 }

 const filteredStores=stores.filter(s=>normalize(s.name).includes(normalize(storeQuery))),filtered=products.filter(p=>normalize(p.name).includes(normalize(query))),preview={...draft,title:'',productIds:ids,categories:draft.categories.filter(c=>availableCategories.includes(c))};
 const validAddress=address.length>=3&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(address)&&!stores.some(s=>s.id!==publishing?.id&&s.domain===address);
 const MediaControl=({field,label,inputRef})=><div className="sb-media-field"><span>{label}</span><div ref={mediaMenu===field?mediaRoot:null} className="sb-media-wrap"><button className="sb-media-button" onClick={()=>field==='banner'?setMediaMenu(mediaMenu?'':field):inputRef.current.click()}>{draft[field]?<img src={draft[field]} alt={label}/>:field==='banner'?<BannerArt preset={draft.bannerPreset}/>:<ImageIcon size={22}/>}<span>{draft[field]?'Trocar imagem':field==='banner'?'Escolher banner':'Carregar imagem'}</span>{field==='banner'&&<ChevronDown size={15}/>}</button>{mediaMenu===field&&<div className="sb-media-menu" role="menu"><button role="menuitem" onClick={()=>{setMediaMenu(null);inputRef.current.click()}}><Upload size={15}/>Subir meu banner</button><button role="menuitem" onClick={()=>{setMediaMenu(null);setGallery(true)}}><ImageIcon size={15}/>Confira a galeria</button></div>}</div><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>upload(e,field)}/>{draft[field]&&<button className="sb-remove" onClick={()=>update(field,'')}>Remover imagem</button>}</div>;
 if(publishBusy)return <section className="sb-publish-page" aria-busy="true"><div className="sb-publish-spinner" role="status" aria-label="Publicando loja"/></section>;
 if(step!==null)return <section className={`supplier-page store-builder sb-builder ${step>0?'sb-builder-editing':''}`}><div className="sb-title"><h1>{draft.id?'Editar loja':'Criar loja'}</h1></div>
 {step===0?<><div className="supplier-grid store-product-grid">{filtered.map(p=><button key={p.id} className="store-product-option" aria-pressed={ids.includes(p.id)} aria-label={`Selecionar ${p.name}`} onClick={()=>{setIds(items=>items.includes(p.id)?items.filter(id=>id!==p.id):[...items,p.id]);if(!ids.includes(p.id)&&!draft.categories.includes(p.category))update('categories',[...draft.categories,p.category])}}><div><img loading="lazy" src={p.image_url} alt=""/><span className="store-product-check">{ids.includes(p.id)&&<Check size={15}/>}</span></div><h2>{p.name}</h2><p>{money.format(p.price_cents/100)}</p></button>)}</div>{!filtered.length&&<p className="supplier-empty">Nenhum produto encontrado</p>}<div className="store-selection-dock"><div className="store-product-search"><HugeiconsIcon icon={Search01Icon} size={18}/><input aria-label="Pesquisar produtos da loja" placeholder="Pesquisar produtos" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="store-primary-action" disabled={!ids.length} onClick={()=>move(1)}>Continuar{ids.length>0&&` (${ids.length})`}</button></div></>:<div className="sb-workspace"><div className="sb-controls">
 {step===1&&<><h2>Escolha seu template</h2><p className="sb-help">Seis formas de apresentar seus produtos</p><div className="sb-template-list">{storeTemplates.map(t=><div role="button" tabIndex={0} key={t.id} aria-label={t.name} aria-pressed={draft.template===t.id} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();update('template',t.id)}}} onClick={()=>update('template',t.id)}><div className="sb-template-thumb" aria-hidden="true" inert><TemplateThumbnail template={t.id} productIds={ids}/></div><div className="sb-template-name"><span>{t.name}</span></div>{draft.template===t.id&&<Check size={16}/>}</div>)}</div></>}
 {step===2&&<><h2>Personalize sua vitrine</h2><p className="sb-help">Cores, imagens e coleções, do seu jeito</p><div className="sb-field-section"><h3>Cores da vitrine</h3>{[['accent','Cor de destaque'],['background','Cor do fundo'],['text','Cor do texto']].map(([key,label])=><ColorControl key={key} label={label} value={draft[key]} onChange={value=>update(key,value)}/>)}</div><div className="sb-field-section"><h3>Imagens da marca</h3><MediaControl field="logo" label="Logo" inputRef={logoInput}/><MediaControl field="banner" label="Banner da apresentação" inputRef={bannerInput}/><MediaControl field="backgroundImage" label="Imagem de fundo" inputRef={backgroundInput}/><label className="sb-range">Escurecer banner <span>{draft.overlay}%</span><input type="range" min="0" max="80" step="5" value={draft.overlay} aria-label="Escurecer banner" style={{'--range-progress':`${draft.overlay/80*100}%`}} onChange={e=>update('overlay',Number(e.target.value))}/></label><p className="sb-overlay-help">Escurece apenas o banner da loja. 0% mantém a imagem original.</p></div><div className="sb-field-section"><h3>Cards e categorias</h3>{[['cardTheme','Tema dos cards'],['categoryTheme','Tema das categorias']].map(([field,label])=><div className="sb-theme-control" key={field}><span>{label}</span><div>{[['light','Claro'],['dark','Escuro']].map(([value,name])=><button aria-pressed={draft[field]===value} key={value} onClick={()=>update(field,value)}>{name}</button>)}</div></div>)}<p className="sb-help">Categorias da vitrine</p><div className="sb-category-options">{availableCategories.map(c=><label key={c}><input type="checkbox" checked={draft.categories.includes(c)} onChange={()=>update('categories',draft.categories.includes(c)?draft.categories.filter(value=>value!==c):[...draft.categories,c])}/>{c}</label>)}</div></div></>}
 {step===3&&<><h2>Identidade da loja</h2><p className="sb-help">Apresente a sua marca e a sua seleção</p><label className="sb-input">Nome da vitrine<input maxLength={60} value={draft.name} onChange={e=>update('name',e.target.value)} placeholder="Ex.: Casa Aurora"/></label><label className="sb-input">Descrição<textarea maxLength={240} rows={4} value={draft.description} onChange={e=>update('description',e.target.value)} placeholder="Conte o que as pessoas encontram na sua vitrine"/><small>{draft.description.length}/240</small></label></>}
 {step===4&&<><h2>Página do produto</h2><p className="sb-help">O layout acompanha o template da sua vitrine.</p>{[['Página',[['background','Fundo da página'],['text','Texto e preço']]],['Imagem',[['imageBackground','Fundo da foto']]],['Oferta',[['offerButton','Botão ver oferta'],['offerText','Texto do botão']]]].map(([label,fields])=><details className="sb-color-group" key={label} open><summary>{label}<ChevronDown size={15}/></summary>{fields.map(([key,title])=><ColorControl key={key} label={title} value={resolveProductColors(draft)[key]} onChange={value=>setDraft(d=>({...d,productColorMode:'custom',productColors:{...d.productColors,[key]:value,...(key==='text'?{priceText:value,backText:value}:{}),...(key==='background'?{infoCard:value,imagePanel:value,priceCard:value,backButton:value}:{})}}))}/>)}</details>)}</>}

 {step===5&&<><h2>Sua vitrine está pronta</h2><p className="sb-help">Confira os detalhes antes de salvar</p><dl className="sb-review">{[['Nome',draft.name],['Template',storeTemplates.find(t=>t.id===draft.template)?.name],['Produtos',`${ids.length} ${ids.length===1?'selecionado':'selecionados'}`],['Categorias',`${preview.categories.length} ${preview.categories.length===1?'categoria':'categorias'}`],['Descrição',draft.description||'Sem descrição']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="sb-help">Salve agora e escolha o endereço em Publicar loja, na página Lojas</p></>}
 <div className="sb-actions"><button onClick={()=>move(step-1)}>Voltar</button><button className="store-primary-action" onClick={()=>step===5?save():move(step+1)}>{step===5?'Salvar loja':'Continuar'}</button></div></div><Preview store={preview} device={device} page={previewPage} onDevice={setDevice} onPage={setPreviewPage}/></div>}
 {gallery&&<Modal label="Galeria de banners" className="sb-gallery-modal" onClose={()=>setGallery(false)}><header><h2>Galeria de banners</h2><ModalCloseButton label="Fechar galeria" onClick={()=>setGallery(false)}/></header><p>Cores lisas para a sua vitrine</p><div className="sb-gallery-grid">{bannerPresets.map(b=><button key={b.id} onClick={()=>{setDraft(d=>({...d,banner:'',bannerPreset:b.id}));setGallery(false)}}><BannerArt preset={b.id}/><span>{b.name}</span></button>)}</div></Modal>}
 </section>;
 return <section className="supplier-page stores-page"><h1>Lojas</h1><div className="supplier-grid stores-grid"><article className="supplier-card store-create-card"><div className="store-logo-placeholder"><HugeiconsIcon icon={Store01Icon} size={42} strokeWidth={1.5}/></div><div className="supplier-card-info"><button onClick={start}>Criar loja</button></div></article>{filteredStores.map(store=><article className="supplier-card store-card sb-store-card" key={store.id} title={store.name}>{store.logo?<img className="store-logo" src={store.logo} alt={`Logo de ${store.name}`}/>:<div className="store-logo-placeholder"><HugeiconsIcon icon={Store01Icon} size={42} strokeWidth={1.5}/></div>}<div className="supplier-card-info sb-store-actions">{store.status==='draft'?<div className="sb-split-action"><button onClick={()=>{setPublishing(store);setAddress(store.domain||'')}}>Publicar loja</button><button aria-label={`Opções de ${store.name}`} aria-haspopup="menu" aria-expanded={options===store.id} onClick={()=>setOptions(options===store.id?null:store.id)}><MoreHorizontal size={18}/></button></div>:<button aria-haspopup="menu" aria-expanded={options===store.id} onClick={()=>setOptions(options===store.id?null:store.id)}>Mais opções</button>}{options===store.id&&<div className="sb-options-menu" role="menu" ref={optionRoot}><button role="menuitem" onClick={()=>edit(store)}>Editar loja</button>{store.url&&<a role="menuitem" href={store.url} target="_blank" rel="noreferrer">Abrir link da loja <ArrowUpRight size={14}/></a>}{store.url&&<button role="menuitem" onClick={async()=>{try{await navigator.clipboard.writeText(store.url);notify('Link copiado','success');setOptions(null)}catch{notify('Não foi possível copiar o link')}}}>Copiar link</button>}<button role="menuitem" onClick={()=>{setOptions(null);setPublishing(store);setAddress(store.domain||'')}}>{store.status==='draft'?'Publicar loja':'Configurar endereço'}</button><button role="menuitem" onClick={()=>remove(store)}>Excluir loja</button></div>}</div></article>)}</div>{storeQuery&&!filteredStores.length&&<p className="supplier-empty">Nenhuma loja encontrada</p>}<div className="supplier-search-dock"><div className="supplier-search"><HugeiconsIcon icon={Search01Icon} size={20}/><input aria-label="Pesquisar lojas" placeholder="Pesquisar lojas" value={storeQuery} onChange={e=>setStoreQuery(e.target.value)}/>{storeQuery&&<button aria-label="Limpar pesquisa" onClick={()=>setStoreQuery('')}><X size={17}/></button>}</div></div>

 {publishing&&<Modal label="Publicar loja" className="sb-publish-modal sb-publish-card" onClose={()=>setPublishing(null)}>
  <header><h2>Publicar loja</h2><ModalCloseButton label="Fechar publicação" onClick={()=>setPublishing(null)}/></header>
  <form onSubmit={publish}>
   <label className="sb-input">Endereço da loja<div className="sb-address"><input autoFocus aria-label="Endereço da loja" maxLength={63} placeholder="sua-loja" value={address} onChange={e=>setAddress(slugify(e.target.value))}/></div></label>
   <p aria-live="polite" className={`sb-availability ${validAddress?'available':''}`}>{!address?'':validAddress?'Endereço válido':address.length<3?'Use pelo menos 3 caracteres':'Esse endereço já está em uso'}</p>
   <div className="sb-actions"><button className="store-primary-action" disabled={!validAddress}>Publicar</button></div>
  </form>
 </Modal>}

 </section>
}
