import {notify} from './Alerts';
import React,{useState,useEffect,useRef} from 'react';
import {X} from 'lucide-react';
import {HugeiconsIcon} from '@hugeicons/react';
import {Search01Icon} from '@hugeicons/core-free-icons';
import {useBackend} from './Backend';
import influencers from './influencers.json';
import videoScripts from './video-scripts.json';
import {buildVideoCaption} from './video-caption.mjs';
const MAX_WORDS=25;
const countWords=text=>(text.match(/\S+/g)||[]).length;
function limitWords(text){const words=[...text.matchAll(/\S+/g)];return words.length>MAX_WORDS?text.slice(0,words[MAX_WORDS-1].index+words[MAX_WORDS-1][0].length):text}
const price=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
export default function Videos({initialInfluencerId}){
 const {products,saved}=useBackend();
 const [step,setStep]=useState(initialInfluencerId?1:0),[influencer,setInfluencer]=useState(()=>influencers.find(i=>i.id===initialInfluencerId)||null),[product,setProduct]=useState(null),[script,setScript]=useState(''),[query,setQuery]=useState(''),[assets,setAssets]=useState([]),[assetError,setAssetError]=useState(''),[copied,setCopied]=useState(false),[retry,setRetry]=useState(0);
 const [captionCopied,setCaptionCopied]=useState(false);
 const caption=buildVideoCaption(product,script,saved[product?.id]||'');
 useEffect(()=>{setCaptionCopied(false)},[caption]);
 const [picker,setPicker]=useState(null),[pickerQuery,setPickerQuery]=useState('');
 const selectionRef=useRef(null),scriptVariants=useRef({});
 function suggestScript(){const options=videoScripts[product.id];if(!options?.length)return;const index=scriptVariants.current[product.id]||0;setScript(options[index]);scriptVariants.current[product.id]=(index+1)%options.length;document.getElementById('video-script')?.focus()}

 useEffect(()=>{if(!picker)return;const dismiss=e=>{if(e.type==='keydown'){if(e.key==='Escape')setPicker(null)}else if(!selectionRef.current?.contains(e.target))setPicker(null)};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',dismiss);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',dismiss)}},[picker]);
 function openPicker(kind){setPicker(current=>current===kind?null:kind);setPickerQuery('')}

 const prompt=influencer&&product?`Crie um vídeo vertical 9:16 em estilo UGC realista. Use a pessoa da imagem de referência como influenciador, preservando seu rosto, aparência e identidade visual. Use exatamente o produto da outra imagem: ${product.name}. Mostre o influenciador segurando e apresentando o produto de forma natural, com proporções reais e sem alterar embalagem, formato ou detalhes. Ambiente cotidiano, luz natural, câmera de celular, enquadramento médio e gestos discretos. Tom ${influencer.tone}. A pessoa deve falar em português brasileiro, com voz natural e sincronização labial, exatamente este roteiro:\n\n${script.trim()}\n\nSem legendas, textos sobrepostos, marcas adicionais ou promessas que não estejam no roteiro. Preserve a aparência do produto durante todo o vídeo.`:'';
 useEffect(()=>{if(step!==3)return;let active=true;const urls=[];setAssets([]);setAssetError('');Promise.all([{url:influencer.image,name:`influenciador-${influencer.id}`},{url:product.image_url,name:`produto-${product.id}`}].map(async item=>{const response=await fetch(item.url);if(!response.ok)throw Error();const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error();if(!active)return null;const url=URL.createObjectURL(blob);urls.push(url);return {url,name:`${item.name}.${blob.type.includes('png')?'png':blob.type.includes('webp')?'webp':'jpg'}`}})).then(result=>{if(active)setAssets(result)}).catch(()=>{if(active){setAssetError('Não foi possível preparar as imagens');notify('Não foi possível preparar as imagens')}});return()=>{active=false;urls.forEach(URL.revokeObjectURL)}},[step,influencer,product,retry]);
 function download(file){const a=document.createElement('a');a.href=file.url;a.download=file.name;document.body.appendChild(a);a.click();a.remove()}
 function move(next){setStep(next);setQuery('');setCopied(false);window.scrollTo({top:0,behavior:'instant'})}
 const normalize=value=>value.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 const list=step===0?influencers.filter(i=>normalize(i.name).includes(normalize(query))):[...products].sort((a,b)=>Number(Boolean(saved[b.id]))-Number(Boolean(saved[a.id]))).filter(p=>normalize(p.name).includes(normalize(query)));
 const pickerItems=(picker==='influencer'?influencers:products).filter(item=>normalize(item.name).includes(normalize(pickerQuery)));
 return <section className="supplier-page videos-page"><h1>Vídeos</h1>
 {step<2&&<><div className="supplier-grid">{list.map(item=><article className={`supplier-card ${step===0?'influencer-card':''}`} key={item.id}><img loading="lazy" src={step===0?item.image:item.image_url} alt={item.name}/><div className="supplier-card-info">{step===1&&<h2>{item.name}</h2>}{step===1&&<p>{price.format(item.price_cents/100)}</p>}<button onClick={()=>{if(step===0){setInfluencer(item);move(1)}else{setProduct(item);move(2)}}}>{step===0?'Criar vídeo':'Escolher produto'}</button></div></article>)}</div>{!list.length&&<p className="supplier-empty">Nenhum resultado encontrado.</p>}<div className="supplier-search-dock"><div className="supplier-search"><HugeiconsIcon icon={Search01Icon} size={20}/><input aria-label={step===0?'Pesquisar influenciadores':'Pesquisar produtos'} placeholder={step===0?'Pesquisar influenciadores':'Pesquisar produtos'} value={query} onChange={e=>setQuery(e.target.value)}/></div></div></>}
 {step>=2&&<div className="video-workspace"><div className="video-selection video-selection-compact" ref={selectionRef}>
 <div><img src={influencer.image} alt="Influenciador selecionado"/><span>Influenciador</span><button aria-label="Trocar influenciador" aria-expanded={picker==='influencer'} onClick={()=>openPicker('influencer')}>Trocar</button></div>
 <div><img src={product.image_url} alt="Produto selecionado"/><span>Produto</span><button aria-label="Trocar produto" aria-expanded={picker==='product'} onClick={()=>openPicker('product')}>Trocar</button></div>
 {picker&&<section className={`video-picker ${picker==='product'?'video-picker-product':''}`} aria-label={picker==='influencer'?'Escolher outro influenciador':'Escolher outro produto'}><header><h2>{picker==='influencer'?'Trocar influenciador':'Trocar produto'}</h2><button aria-label="Fechar seleção" onClick={()=>setPicker(null)}><X size={18}/></button></header><div className="video-picker-search"><HugeiconsIcon icon={Search01Icon} size={18}/><input autoFocus aria-label="Pesquisar na seleção" placeholder={picker==='influencer'?'Pesquisar influenciadores':'Pesquisar produtos'} value={pickerQuery} onChange={e=>setPickerQuery(e.target.value)}/></div><div className="video-picker-grid">{pickerItems.map(item=><button key={item.id} aria-label={`Selecionar ${item.name}`} aria-pressed={item.id===(picker==='influencer'?influencer.id:product.id)} onClick={()=>{if(picker==='influencer')setInfluencer(item);else setProduct(item);setCopied(false);setPicker(null)}}><img loading="lazy" src={picker==='influencer'?item.image:item.image_url} alt=""/>{picker==='product'&&<span>{item.name}</span>}</button>)}</div>{!pickerItems.length&&<p className="supplier-empty">Nenhum resultado encontrado.</p>}</section>}
 </div>
 {step===2?<form className="video-script-form" onSubmit={e=>{e.preventDefault();if(script.trim()&&countWords(script)<=MAX_WORDS)move(3)}}><div className="video-script-heading"><label htmlFor="video-script">Roteiro do vídeo</label></div><p id="video-script-help">Escreva uma fala curta em português, com até 25 palavras.</p><textarea id="video-script" autoFocus required rows={5} aria-describedby="video-script-help video-word-count" placeholder="Escreva a fala sobre o produto..." value={script} onChange={e=>setScript(limitWords(e.target.value))}/><div className="video-form-bottom"><span id="video-word-count" aria-live="polite">{countWords(script)}/{MAX_WORDS} palavras</span><div className="video-script-actions"><span className="tooltip-control tooltip-end"><button type="button" className="video-script-ai" aria-label="Gerar com IA" aria-describedby="video-script-ai-tooltip" onClick={suggestScript}><span className="video-ai-mask" aria-hidden="true"/></button><span className="control-tooltip" role="tooltip" id="video-script-ai-tooltip">Gerar com IA</span></span><button disabled={!script.trim()}>Gerar prompt</button></div></div></form>:<div className="video-prompt-panel"><div className="video-prompt-title"><h2>Seu prompt está pronto</h2><button onClick={()=>move(2)}>Editar roteiro</button></div><textarea aria-label="Prompt gerado" readOnly value={prompt} rows={11} onFocus={e=>e.target.select()}/><div className="video-prompt-actions"><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(caption);setCaptionCopied(true);setTimeout(()=>setCaptionCopied(false),2000)}catch{notify('Não foi possível copiar a legenda');document.querySelector('[aria-label="Legenda do vídeo"]')?.focus()}}}>{captionCopied?'Legenda copiada':'Copiar legenda'}</button><button onClick={async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{notify('Não foi possível copiar o prompt');document.querySelector('[aria-label="Prompt gerado"]')?.focus()}}}>{copied?'Prompt copiado':'Copiar prompt'}</button>{assets.length===2?<a href="https://flow.google.com/" target="_blank" rel="noreferrer" onClick={()=>assets.forEach(download)}>Baixar imagens e abrir Google Flow</a>:<button disabled={!assetError} onClick={()=>setRetry(v=>v+1)}>{assetError?'Tentar preparar imagens novamente':'Preparando imagens...'}</button>}</div><div className="video-caption-preview"><label htmlFor="video-caption">Legenda do vídeo</label><textarea id="video-caption" aria-label="Legenda do vídeo" readOnly value={caption} rows={5} onFocus={e=>e.target.select()}/></div></div>}
 </div>}
 </section>
}
