import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import assert from 'node:assert/strict';
const source=(await readFile(new URL('../supabase/functions/prime-account/index.ts',import.meta.url),'utf8')).replace(/^import .*;\n/,'').replace('status:number,value:unknown','status,value').replace(/\)!([,)])/g,')$1');
function setup(valid=true){let handler;const deleted=[];const scheduled=[];new Function('Deno','createClient',source)({serve:fn=>handler=fn,env:{get:key=>({SUPABASE_URL:'https://example.test',SUPABASE_SERVICE_ROLE_KEY:'test-only'}[key])}},()=>({auth:{getUser:async()=>({data:{user:valid?{id:'owner-id',email:'owner@example.test'}:null},error:valid?null:new Error('Invalid')}),admin:{deleteUser:async id=>{deleted.push(id);return {error:null}},signOut:async()=>({error:null})}},rpc:async(name,args)=>{scheduled.push({name,args});return {data:'2026-11-04T00:00:00Z',error:null}}}));return {handler,deleted,scheduled}}
const req=(body,token='Bearer test-only',origin='http://localhost:5174')=>new Request('https://example.test',{method:'POST',headers:{authorization:token,origin,'content-type':'application/json'},body:JSON.stringify(body)});
test('preflight has no body and does not call privileged operations',async()=>{const {handler,deleted}=setup();const res=await handler(new Request('https://example.test',{method:'OPTIONS',headers:{origin:'http://localhost:5174'}}));assert.equal(res.status,204);assert.equal(await res.text(),'');assert.deepEqual(deleted,[])});
test('rejects invalid auth, mismatched email and unapproved origins without deletion',async()=>{
 for(const [valid,body,origin,status] of [[false,{action:'delete-account',email:'owner@example.test'},undefined,401],[true,{action:'delete-account',email:'other@example.test'},undefined,400],[true,{action:'delete-account',email:'owner@example.test'},'https://attacker.test',403]]){const {handler,deleted}=setup(valid);assert.equal((await handler(req(body,'Bearer test-only',origin))).status,status);assert.deepEqual(deleted,[])}
});
test('ignores payload user ID and binds successful request to verified caller',async()=>{const {handler,deleted,scheduled}=setup();const res=await handler(req({action:'delete-account',email:'owner@example.test',user_id:'victim-id'}));assert.equal(res.status,200);assert.deepEqual(deleted,[]);assert.deepEqual(scheduled,[{name:'request_prime_account_deletion',args:{p_user_id:'owner-id',p_email:'owner@example.test'}}]);assert.equal((await res.json()).scheduled,true)});
