import test from 'node:test';
import assert from 'node:assert/strict';
import {createConsentStore,CONSENT_KEY,analyticsDetails} from '../src/cookie-consent.mjs';
function setup({cookies=true,storage=true}={}){const values=new Map();let cookie='',changed=0;const doc={get cookie(){return cookie},set cookie(value){if(cookies)cookie=value.split(';')[0]}};const local={getItem:key=>{if(!storage)throw Error();return values.get(key)||null},setItem:(key,value)=>{if(!storage)throw Error();values.set(key,value)}};return {doc,local,values,store:createConsentStore({document:doc,storage:local,secure:true,dispatch:()=>changed++}),changes:()=>changed}}
test('first visit requires a choice; accepting survives component recreation and reload',()=>{const env=setup();assert.equal(env.store.read(),null);env.store.save({analytics:true,advertising:true});const fresh=createConsentStore({document:env.doc,storage:env.local});assert.equal(fresh.read().analytics,true);assert.equal(env.changes(),1);assert.match(env.doc.cookie,/prime_cookie_preferences=/)});
test('rejecting or closing persists essentials only; reopening settings does not imply consent',()=>{const {store}=setup();store.save({analytics:false,advertising:false});assert.equal(store.read().essential,true);assert.equal(store.read().analytics,false);assert.equal(store.preferences().advertising,false)});
test('withdrawal replaces prior consent and blocks optional collection',()=>{const {store}=setup();store.save({analytics:true,advertising:true});store.save({analytics:false,advertising:false});assert.equal(store.read().analytics,false);assert.equal(store.read().advertising,false)});
test('preserves previous choices; corrupted values cannot enable tracking',()=>{const {store,values}=setup();values.set(CONSENT_KEY,JSON.stringify({essential:true,analytics:false,advertising:true}));assert.equal(store.read().advertising,true);values.set(CONSENT_KEY,'{');assert.equal(store.read(),null);values.set(CONSENT_KEY,JSON.stringify({analytics:'true',advertising:true}));assert.equal(store.read(),null)});
test('uses cookie when local storage is blocked, and local storage when cookies are blocked',()=>{for(const options of [{storage:false},{cookies:false}]){const {store}=setup(options);store.save({analytics:false,advertising:false});assert.equal(store.read().analytics,false)}assert.throws(()=>setup({cookies:false,storage:false}).store.save({}),/salvar/)});
test('device details describe the browser without manufacturing IP or collecting full URL',()=>{const details=analyticsDetails({navigator:{userAgent:'iPhone Mobile',platform:'iPhone',language:'pt-BR'},screen:{width:390,height:844},timezone:'America/Sao_Paulo'});assert.equal(details.device,'mobile');assert.equal(details.screen_width,390);assert.equal('ip' in details,false);assert.equal('url' in details,false)});
